services:
  db:
    container_name: postgres_database
    image: postgres:16.10-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crud
    volumes:
      - ./postgres:/var/lib/postgresql/data